sudo: false
language: ruby
rvm:
  - 2.1.5

bundler_args: --path=vendor/bundle --without heroku

before_script:
  - sh -c "psql -c 'create database ffcrm_endpoint_test;' -U postgres"

# Run specs
script: "bundle exec rake"
