development:
  adapter: postgresql
  encoding: unicode
  database: ffcrm_endpoint_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ffcrm_endpoint_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ffcrm_endpoint_production
  pool: 5
